version: "3.5"

services:
  caddy:
    build: ./caddy
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    volumes:
      - ~/docker-persistence/caddy:/data
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./spa-builder/dist:/dist
  # web:
  #   environment:
  #   build: ../../app
  #   expose:
  #     - "8080"

# vim:set et ts=2 sw=2: